### ISSUE TITLE
Dynamic variable to view function

### ISSUE THREAD

**Issue by ananthi23** [prymitive/bootstrap-breadcrumbs#32]
How to assign dynamic variable as viewname in {% breadcrumb forum_name "topic" parameter=forum_name %}
instead of  "topic" i need to use "topic"+dynamic variable.

how to do like that?

**Comment by prymitive** [comment]
From http://django-bootstrap-breadcrumbs.readthedocs.io/en/latest/#breadcrumb

```
viewname - Any string that can be resolved into a view url with django reverse() function or a django Model instance with implemented get_absolute_url() method.
```

so you can pass a model instance that will return the right url in `get_absolute_url()`, see https://github.com/prymitive/bootstrap-breadcrumbs/blob/master/tests/test_templatetags.py#L190 for example. Django docs are at https://docs.djangoproject.com/en/1.11/ref/models/instances/#get-absolute-url

It's been a while since I've touched this code, but it's likely that simply passing a variable as `viewname` argument would also work.
